name: Sync images

on:
  workflow_dispatch:
  schedule:
    # every day at 8, 14 pacific
    - cron: "0 0,6 * * *"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./auth.yaml
          images_file: ./images.yaml
          version: latest
          proc: 8
          retry: 3
        env:
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}